"""FastHTML component helpers for the Web Audio API manager"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/components.ipynb.

# %% auto #0
__all__ = ['DEFAULT_STATIC_MOUNT_PATH', 'render_audio_urls_input', 'render_web_audio_script', 'mount_web_audio_static',
           'render_initial_speed_sync', 'render_speed_selector']

# %% ../nbs/components.ipynb #c3d4e5f6
import json
from importlib.resources import files as _pkg_files
from typing import Any, List, Optional

from fasthtml.common import Div, Input, Label, Option, Script, Select, Span
from starlette.routing import Mount
from starlette.staticfiles import StaticFiles

# DaisyUI components
from cjm_fasthtml_daisyui.components.data_input.select import select, select_sizes
from cjm_fasthtml_daisyui.utilities.semantic_colors import text_dui

from cjm_fasthtml_design_system.text_tiers import text_tiers

# Tailwind utilities
from cjm_fasthtml_tailwind.utilities.spacing import m
from cjm_fasthtml_tailwind.utilities.typography import font_size
from cjm_fasthtml_tailwind.utilities.flexbox_and_grid import flex_display, items
from cjm_fasthtml_tailwind.core.base import combine_classes

from .models import WebAudioConfig, WebAudioHtmlIds
from .js import generate_web_audio_js, DEFAULT_WORKLET_URL, PLAYBACK_SPEEDS

# %% ../nbs/components.ipynb #e5f6a7b8
def render_audio_urls_input(
    config: WebAudioConfig,    # Instance configuration
    audio_urls: List[str],     # Audio file URLs to load
    oob: bool = False,         # Whether to render as OOB swap
) -> Any:  # Hidden input element with JSON-encoded URLs
    """Render a hidden input storing audio URLs as JSON."""
    return Input(
        type="hidden",
        id=WebAudioHtmlIds.audio_urls_input(config.namespace),
        value=json.dumps(audio_urls),
        hx_swap_oob="true" if oob else None,
    )

# %% ../nbs/components.ipynb #a7b8c9d0
def render_web_audio_script(
    config: WebAudioConfig,        # Instance configuration
    focus_input_id: str,           # Hidden input ID for focused index
    card_stack_id: str,            # Card stack container ID
    nav_down_btn_id: str = "",     # Nav down button ID (for auto-navigate)
) -> Any:  # Script element with complete Web Audio JS
    """Render the complete Web Audio API script for a configured instance."""
    js = generate_web_audio_js(
        config=config,
        focus_input_id=focus_input_id,
        card_stack_id=card_stack_id,
        nav_down_btn_id=nav_down_btn_id,
    )
    return Script(js)

# %% ../nbs/components.ipynb #baf887ff
# Default mount path; must stay in sync with DEFAULT_WORKLET_URL in cjm_fasthtml_web_audio.js
DEFAULT_STATIC_MOUNT_PATH = "/static/cjm-web-audio"

def mount_web_audio_static(
    app,                                            # FastHTML/Starlette app
    mount_path: str = DEFAULT_STATIC_MOUNT_PATH,    # URL prefix to mount static dir at
) -> str:                                           # URL of the SoundTouch worklet processor
    """Mount the library's vendored static assets (SoundTouch worklet, license).
    
    Inserts the Mount at `app.routes[0]` so it's matched BEFORE any catch-all
    routes FastHTML may have registered. Returns the URL where the SoundTouch
    worklet processor is served; when `mount_path` is the default the URL equals
    `DEFAULT_WORKLET_URL` — so `WebAudioConfig(enable_speed=True)` with no explicit
    `worklet_url` just works.
    """
    static_dir = str(_pkg_files("cjm_fasthtml_web_audio") / "static")
    mount = Mount(
        mount_path,
        app=StaticFiles(directory=static_dir),
        name="cjm-web-audio-static",
    )
    app.routes.insert(0, mount)
    return f"{mount_path.rstrip('/')}/soundtouch-processor.js"

# %% ../nbs/components.ipynb #6e8e98ca
def render_initial_speed_sync(
    config: WebAudioConfig,     # Instance configuration
    speed: float,               # Persisted playback speed (e.g. from step state)
) -> Any:                       # Script element (empty if speed is default or speed is disabled)
    """Render a <Script> that syncs the JS state's playbackSpeed to `speed` after insertion.
    
    Polls briefly (~1 second, 20ms intervals) for `window.set{Ns}Speed` so the helper
    works regardless of whether the web-audio script or the toolbar script runs first.
    Returns an empty Script when `speed == 1.0` (state_init already defaults to 1.0)
    or when `config.enable_speed` is False.
    """
    if not config.enable_speed or speed == 1.0:
        return Script("")
    ns = config.ns
    return Script(f"""
    (function() {{
      var tries = 0;
      var apply = function() {{
        if (window.set{ns}Speed) {{
          window.set{ns}Speed({speed});
        }} else if (tries++ < 50) {{
          setTimeout(apply, 20);
        }}
      }};
      apply();
    }})();
    """)

# %% ../nbs/components.ipynb #407682f8
def render_speed_selector(
    config: WebAudioConfig,          # Instance configuration (must have enable_speed=True for sync to fire)
    current_speed: float = 1.0,      # Current / persisted playback speed
    change_url: str = "",            # URL to POST speed changes to (empty → no server persist)
    label: Optional[str] = "Speed:", # Leading label text (None/"" → omit label span)
) -> Any:                            # Div(Span?, Select, sync Script)
    """Render the shared playback speed selector.

    Emits a DaisyUI `<select>` whose `onchange` calls `window.set{Ns}Speed(...)` for
    immediate JS state update. When `change_url` is provided, also POSTs to that URL
    via HTMX for server-side persistence (consumers typically return `Script(generate_speed_change_js(...))`).

    Also emits `render_initial_speed_sync(config, current_speed)` so the JS state
    reconciles to `current_speed` on initial render and OOB swaps — the `<option selected>`
    attribute only restores the dropdown visually.
    """
    ns = config.ns
    options = [
        Option(lbl, value=str(s), selected=(s == current_speed))
        for s, lbl in PLAYBACK_SPEEDS
    ]

    htmx_attrs = {}
    if change_url:
        htmx_attrs = {
            "hx_post": change_url,
            "hx_trigger": "change",
            "hx_swap": "none",
        }

    onchange_js = f"if(window.set{ns}Speed) window.set{ns}Speed(parseFloat(this.value));"

    children = []
    if label:
        children.append(Span(
            label,
            cls=combine_classes(font_size.sm, text_tiers.secondary, m.r(2)),
        ))
    children.append(Select(
        *options,
        id=WebAudioHtmlIds.speed_select(config.namespace),
        name="speed",
        cls=combine_classes(select, select_sizes.sm),
        onchange=onchange_js,
        **htmx_attrs,
    ))
    # Sync JS state to current_speed (no-op when speed == 1.0 or enable_speed is False)
    children.append(render_initial_speed_sync(config, current_speed))

    return Div(*children, cls=combine_classes(flex_display, items.center))
