"""FastHTML component helpers for the Web Audio API manager"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/components.ipynb.

# %% auto #0
__all__ = ['render_audio_urls_input', 'render_web_audio_script']

# %% ../nbs/components.ipynb #c3d4e5f6
import json
from typing import Any, List

from fasthtml.common import Input, Script

from .models import WebAudioConfig, WebAudioHtmlIds
from .js import generate_web_audio_js

# %% ../nbs/components.ipynb #e5f6a7b8
def render_audio_urls_input(
    config: WebAudioConfig,    # Instance configuration
    audio_urls: List[str],     # Audio file URLs to load
    oob: bool = False,         # Whether to render as OOB swap
) -> Any:  # Hidden input element with JSON-encoded URLs
    """Render a hidden input storing audio URLs as JSON."""
    return Input(
        type="hidden",
        id=WebAudioHtmlIds.audio_urls_input(config.namespace),
        value=json.dumps(audio_urls),
        hx_swap_oob="true" if oob else None,
    )

# %% ../nbs/components.ipynb #a7b8c9d0
def render_web_audio_script(
    config: WebAudioConfig,        # Instance configuration
    focus_input_id: str,           # Hidden input ID for focused index
    card_stack_id: str,            # Card stack container ID
    nav_down_btn_id: str = "",     # Nav down button ID (for auto-navigate)
) -> Any:  # Script element with complete Web Audio JS
    """Render the complete Web Audio API script for a configured instance."""
    js = generate_web_audio_js(
        config=config,
        focus_input_id=focus_input_id,
        card_stack_id=card_stack_id,
        nav_down_btn_id=nav_down_btn_id,
    )
    return Script(js)
