"""FastHTML component helpers for the Web Audio API manager"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/components.ipynb.

# %% auto #0
__all__ = ['DEFAULT_STATIC_MOUNT_PATH', 'render_audio_urls_input', 'render_web_audio_script', 'mount_web_audio_static',
           'render_initial_speed_sync']

# %% ../nbs/components.ipynb #c3d4e5f6
import json
from importlib.resources import files as _pkg_files
from typing import Any, List

from fasthtml.common import Input, Script
from starlette.routing import Mount
from starlette.staticfiles import StaticFiles

from .models import WebAudioConfig, WebAudioHtmlIds
from .js import generate_web_audio_js, DEFAULT_WORKLET_URL

# %% ../nbs/components.ipynb #e5f6a7b8
def render_audio_urls_input(
    config: WebAudioConfig,    # Instance configuration
    audio_urls: List[str],     # Audio file URLs to load
    oob: bool = False,         # Whether to render as OOB swap
) -> Any:  # Hidden input element with JSON-encoded URLs
    """Render a hidden input storing audio URLs as JSON."""
    return Input(
        type="hidden",
        id=WebAudioHtmlIds.audio_urls_input(config.namespace),
        value=json.dumps(audio_urls),
        hx_swap_oob="true" if oob else None,
    )

# %% ../nbs/components.ipynb #a7b8c9d0
def render_web_audio_script(
    config: WebAudioConfig,        # Instance configuration
    focus_input_id: str,           # Hidden input ID for focused index
    card_stack_id: str,            # Card stack container ID
    nav_down_btn_id: str = "",     # Nav down button ID (for auto-navigate)
) -> Any:  # Script element with complete Web Audio JS
    """Render the complete Web Audio API script for a configured instance."""
    js = generate_web_audio_js(
        config=config,
        focus_input_id=focus_input_id,
        card_stack_id=card_stack_id,
        nav_down_btn_id=nav_down_btn_id,
    )
    return Script(js)

# %% ../nbs/components.ipynb #baf887ff
# Default mount path; must stay in sync with DEFAULT_WORKLET_URL in cjm_fasthtml_web_audio.js
DEFAULT_STATIC_MOUNT_PATH = "/static/cjm-web-audio"

def mount_web_audio_static(
    app,                                            # FastHTML/Starlette app
    mount_path: str = DEFAULT_STATIC_MOUNT_PATH,    # URL prefix to mount static dir at
) -> str:                                           # URL of the SoundTouch worklet processor
    """Mount the library's vendored static assets (SoundTouch worklet, license).
    
    Inserts the Mount at `app.routes[0]` so it's matched BEFORE any catch-all
    routes FastHTML may have registered. Returns the URL where the SoundTouch
    worklet processor is served; when `mount_path` is the default the URL equals
    `DEFAULT_WORKLET_URL` — so `WebAudioConfig(enable_speed=True)` with no explicit
    `worklet_url` just works.
    """
    static_dir = str(_pkg_files("cjm_fasthtml_web_audio") / "static")
    mount = Mount(
        mount_path,
        app=StaticFiles(directory=static_dir),
        name="cjm-web-audio-static",
    )
    app.routes.insert(0, mount)
    return f"{mount_path.rstrip('/')}/soundtouch-processor.js"

# %% ../nbs/components.ipynb #6e8e98ca
def render_initial_speed_sync(
    config: WebAudioConfig,     # Instance configuration
    speed: float,               # Persisted playback speed (e.g. from step state)
) -> Any:                       # Script element (empty if speed is default or speed is disabled)
    """Render a <Script> that syncs the JS state's playbackSpeed to `speed` after insertion.
    
    Polls briefly (~1 second, 20ms intervals) for `window.set{Ns}Speed` so the helper
    works regardless of whether the web-audio script or the toolbar script runs first.
    Returns an empty Script when `speed == 1.0` (state_init already defaults to 1.0)
    or when `config.enable_speed` is False.
    """
    if not config.enable_speed or speed == 1.0:
        return Script("")
    ns = config.ns
    return Script(f"""
    (function() {{
      var tries = 0;
      var apply = function() {{
        if (window.set{ns}Speed) {{
          window.set{ns}Speed({speed});
        }} else if (tries++ < 50) {{
          setTimeout(apply, 20);
        }}
      }};
      apply();
    }})();
    """)
