"""JavaScript generation for the Web Audio API manager"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/js.ipynb.

# %% auto #0
__all__ = ['DEFAULT_WORKLET_URL', 'PLAYBACK_SPEEDS', 'generate_state_init', 'generate_init_audio', 'generate_stop_audio',
           'generate_play_segment', 'generate_optional_features', 'generate_speed_change_js', 'generate_focus_change',
           'generate_htmx_settle_handler', 'generate_web_audio_js']

# %% ../nbs/js.ipynb #c3d4e5f6
from .models import WebAudioConfig, WebAudioHtmlIds

# %% ../nbs/js.ipynb #e5f6a7b8
def generate_state_init(
    config: WebAudioConfig,  # Instance configuration
) -> str:  # JS code that initializes the state object
    """Generate JS code to initialize the namespaced state object."""
    sk = config.state_key
    
    speed_fields = ""
    if config.enable_speed:
        speed_fields += f"\n    {sk}.playbackSpeed = 1.0;"
        speed_fields += f"\n    {sk}.workletRegistered = false;"
        speed_fields += f"\n    {sk}.workletNode = null;"
    if config.enable_replay:
        speed_fields += f"\n    {sk}.currentSegment = null;"
    if config.enable_auto_nav:
        speed_fields += f"\n    {sk}.autoNavigate = false;"
    
    return f"""// Web Audio Manager: {config.namespace}
    window.{sk} = window.{sk} || {{}};
    {sk}.buffers = [];
    {sk}.ctx = null;
    {sk}.currentSource = null;
    {sk}.loading = false;
    {sk}.error = null;
    {sk}.pendingPlay = null;
    {sk}.playTimeout = null;
    {sk}.lastPlayedIndex = null;{speed_fields}
    window.DEBUG_{config.namespace.upper()}_AUDIO = false;"""

# %% ../nbs/js.ipynb #a7b8c9d0
DEFAULT_WORKLET_URL = "/static/cjm-web-audio/soundtouch-processor.js"

def generate_init_audio(
    config: WebAudioConfig,  # Instance configuration
) -> str:  # JS init function
    """Generate JS function that loads and decodes audio files in parallel.
    
    When `config.enable_speed=True`, the SoundTouch worklet processor is registered
    on the AudioContext before decoding. On registration failure, `workletRegistered`
    remains false and the play path falls back to naive (pitch-shifting) playbackRate.
    """
    sk = config.state_key
    ns = config.ns
    urls_input_id = WebAudioHtmlIds.audio_urls_input(config.namespace)
    dbg = f"DEBUG_{config.namespace.upper()}_AUDIO"
    
    # Worklet registration block (only emitted when speed is enabled)
    worklet_register = ""
    if config.enable_speed:
        worklet_url = config.worklet_url or DEFAULT_WORKLET_URL
        worklet_register = f"""
            // Register SoundTouch worklet (once per context; idempotent)
            if (!s.workletRegistered) {{
                try {{
                    await s.ctx.audioWorklet.addModule('{worklet_url}');
                    s.workletRegistered = true;
                    if (window.{dbg}) console.log('[{ns}Audio] SoundTouch worklet registered');
                }} catch (e) {{
                    console.error('[{ns}Audio] Worklet register failed; speed changes will shift pitch:', e);
                }}
            }}
            """
    
    return f"""window.init{ns}Audio = async function() {{
        var s = window.{sk};
        if (s.buffers.length > 0 || s.loading) return;
        
        var urlsInput = document.getElementById('{urls_input_id}');
        if (!urlsInput || !urlsInput.value) {{
            console.warn('[{ns}Audio] No audio URLs input found');
            return;
        }}
        
        var urls;
        try {{ urls = JSON.parse(urlsInput.value); }}
        catch(e) {{ console.error('[{ns}Audio] Invalid URL JSON:', e); return; }}
        
        if (!Array.isArray(urls) || urls.length === 0) {{
            console.warn('[{ns}Audio] Empty audio URLs array');
            return;
        }}
        
        s.loading = true;
        try {{
            s.ctx = s.ctx || new (window.AudioContext || window.webkitAudioContext)();
            {worklet_register}
            if (window.{dbg}) console.log('[{ns}Audio] Loading ' + urls.length + ' audio file(s)...');
            
            var decodePromises = urls.map(function(url, idx) {{
                return fetch(url)
                    .then(function(r) {{ return r.arrayBuffer(); }})
                    .then(function(buf) {{ return s.ctx.decodeAudioData(buf); }})
                    .then(function(decoded) {{
                        if (window.{dbg}) console.log('[{ns}Audio] Decoded buffer ' + idx + ': ' +
                            decoded.duration.toFixed(1) + 's, ' + decoded.sampleRate + 'Hz, ' +
                            decoded.numberOfChannels + 'ch');
                        return {{ index: idx, buffer: decoded }};
                    }});
            }});
            
            var results = await Promise.all(decodePromises);
            
            // Store buffers at their original indices
            s.buffers = new Array(urls.length);
            results.forEach(function(r) {{ s.buffers[r.index] = r.buffer; }});
            
            if (window.{dbg}) console.log('[{ns}Audio] All ' + s.buffers.length + ' buffers loaded');
            
            // Play pending request if queued
            if (s.pendingPlay) {{
                var p = s.pendingPlay;
                s.pendingPlay = null;
                window.play{ns}Segment(p.bufferIndex, p.start, p.end, p.indicator);
            }}
        }} catch(e) {{
            s.error = e;
            console.error('[{ns}Audio] Load error:', e);
        }} finally {{
            s.loading = false;
        }}
    }};"""

# %% ../nbs/js.ipynb #c9d0e1f2
def generate_stop_audio(
    config: WebAudioConfig,  # Instance configuration
) -> str:  # JS stop function
    """Generate JS function that stops current playback."""
    sk = config.state_key
    ns = config.ns
    
    worklet_cleanup = ""
    if config.enable_speed:
        worklet_cleanup = f"""
        if (s.workletNode) {{
            try {{ s.workletNode.disconnect(); }} catch(e) {{}}
            s.workletNode = null;
        }}"""
    
    return f"""window.stop{ns}Audio = function() {{
        var s = window.{sk};
        if (s.currentSource) {{
            try {{ s.currentSource.stop(); }} catch(e) {{}}
            s.currentSource.disconnect();
            s.currentSource = null;
        }}{worklet_cleanup}
        if (s.playTimeout) {{
            clearTimeout(s.playTimeout);
            s.playTimeout = null;
        }}
    }};"""

# %% ../nbs/js.ipynb #e1f2a3b4
def generate_play_segment(
    config: WebAudioConfig,  # Instance configuration
    nav_down_btn_id: str = "",  # Nav down button ID (for auto-navigate)
) -> str:  # JS play function
    """Generate JS function that plays a segment from a specific buffer.
    
    When `config.enable_speed=True` and speed != 1.0 and the SoundTouch worklet is
    registered, audio flows BufferSource -> SoundTouchNode -> destination, with
    pitch auto-compensated by the worklet so tempo changes preserve pitch. Otherwise
    audio flows BufferSource -> destination (naive path; pitch shifts at non-1x).
    """
    sk = config.state_key
    ns = config.ns
    dbg = f"DEBUG_{config.namespace.upper()}_AUDIO"
    
    if config.enable_speed:
        connection_block = f"""
        var speed = s.playbackSpeed || 1.0;
        var src = s.ctx.createBufferSource();
        src.buffer = buffer;
        
        if (speed !== 1.0 && s.workletRegistered) {{
            // Pitch-preserving path: source (at `speed`) -> SoundTouchNode -> destination
            // SoundTouch divides pitch by playbackRate internally, so output is tempo-shifted with pitch preserved
            src.playbackRate.value = speed;
            var stNode = new AudioWorkletNode(s.ctx, 'soundtouch-processor', {{
                numberOfInputs: 1,
                numberOfOutputs: 1,
                outputChannelCount: [2]
            }});
            stNode.parameters.get('playbackRate').value = speed;
            stNode.parameters.get('pitch').value = 1.0;
            stNode.parameters.get('tempo').value = 1.0;
            stNode.parameters.get('rate').value = 1.0;
            src.connect(stNode);
            stNode.connect(s.ctx.destination);
            s.workletNode = stNode;
        }} else {{
            // 1.0x fast path OR worklet-not-registered fallback (naive playbackRate; pitch shifts)
            if (speed !== 1.0) src.playbackRate.value = speed;
            src.connect(s.ctx.destination);
            s.workletNode = null;
        }}"""
        timeout_expr = "(duration / speed) * 1000"
    else:
        connection_block = """
        var src = s.ctx.createBufferSource();
        src.buffer = buffer;
        src.connect(s.ctx.destination);"""
        timeout_expr = "duration * 1000"
    
    # Store current segment for replay
    replay_store = ""
    if config.enable_replay:
        replay_store = f"s.currentSegment = {{bufferIndex: bufferIndex, start: start, end: end, indicator: indicator}};"
    
    # Auto-navigate on completion
    auto_nav = ""
    if config.enable_auto_nav and nav_down_btn_id:
        auto_nav = f"""
            if (s.autoNavigate) {{
                var navBtn = document.getElementById('{nav_down_btn_id}');
                if (navBtn) navBtn.click();
            }}"""
    
    return f"""window.play{ns}Segment = function(bufferIndex, start, end, indicator) {{
        var s = window.{sk};
        
        // Queue if not loaded yet
        if (s.buffers.length === 0) {{
            s.pendingPlay = {{bufferIndex: bufferIndex, start: start, end: end, indicator: indicator}};
            window.init{ns}Audio();
            return;
        }}
        
        // Resume suspended context (autoplay policy)
        if (s.ctx && s.ctx.state === 'suspended') s.ctx.resume();
        
        // Stop previous
        window.stop{ns}Audio();
        
        // Validate buffer index
        var bi = bufferIndex || 0;
        if (bi < 0 || bi >= s.buffers.length) {{
            console.warn('[{ns}Audio] Invalid buffer index: ' + bi);
            return;
        }}
        
        var buffer = s.buffers[bi];
        var clampStart = Math.max(0, Math.min(start, buffer.duration));
        var clampEnd = Math.max(clampStart, Math.min(end, buffer.duration));
        var duration = clampEnd - clampStart;
        if (duration <= 0) return;
        
        {replay_store}
        {connection_block}
        s.currentSource = src;
        src.start(0, clampStart, duration);
        
        if (window.{dbg}) console.log('[{ns}Audio] Playing buffer ' + bi + ': ' +
            clampStart.toFixed(2) + 's -> ' + clampEnd.toFixed(2) + 's');
        
        s.playTimeout = setTimeout(function() {{
            if (indicator) indicator.style.visibility = 'hidden';{auto_nav}
        }}, {timeout_expr});
    }};"""

# %% ../nbs/js.ipynb #a3b4c5d6
# Discrete playback speeds available via the shared selector + cycle helpers.
# Tuple entries are (value, label); values must be sorted ascending (cycle helpers rely on it).
PLAYBACK_SPEEDS = [
    (0.5, "0.5x"),
    (0.75, "0.75x"),
    (1.0, "1x"),
    (1.25, "1.25x"),
    (1.5, "1.5x"),
    (2.0, "2x"),
    (2.5, "2.5x"),
    (3.0, "3x"),
]


def _speed_values_js_array() -> str:  # JS array literal of speed values
    """Render PLAYBACK_SPEEDS values as a JS array literal (e.g., '[0.5, 0.75, ...]')."""
    return "[" + ", ".join(str(s) for s, _ in PLAYBACK_SPEEDS) + "]"


def generate_optional_features(
    config: WebAudioConfig,  # Instance configuration
) -> str:  # JS for optional feature functions (empty if none enabled)
    """Generate JS for optional features based on config flags.

    When `config.enable_speed=True`, emits `set{Ns}Speed`, `cycle{Ns}SpeedTo`,
    `cycle{Ns}SpeedUp`, `cycle{Ns}SpeedDown`. The cycle helpers drive the shared
    speed `<select>` via a synthetic `change` event so the dropdown, JS state, and
    HTMX-backed server persistence stay in sync through a single code path.
    """
    sk = config.state_key
    ns = config.ns
    parts = []

    if config.enable_speed:
        speed_select_id = WebAudioHtmlIds.speed_select(config.namespace)
        speeds_js = _speed_values_js_array()
        # cycle{ns}SpeedTo selects by parsed option value (not string equality) because
        # Python str(1.0) == "1.0" but JS String(1.0) === "1" — setting sel.value to a
        # mismatched string blanks the dropdown. Parsed-value matching is roundtrip-safe.
        parts.append(f"""window.set{ns}Speed = function(speed) {{
        window.{sk}.playbackSpeed = speed;
    }};

    window.cycle{ns}SpeedTo = function(speed) {{
        var sel = document.getElementById('{speed_select_id}');
        if (sel) {{
            var matched = false;
            for (var i = 0; i < sel.options.length; i++) {{
                if (Math.abs(parseFloat(sel.options[i].value) - speed) < 1e-6) {{
                    sel.selectedIndex = i;
                    matched = true;
                    break;
                }}
            }}
            if (matched) {{
                // Dispatch change so inline onchange fires set{ns}Speed AND HTMX persists
                sel.dispatchEvent(new Event('change', {{bubbles: true}}));
            }} else if (window.set{ns}Speed) {{
                // No matching option in the rendered dropdown; update JS state directly
                window.set{ns}Speed(speed);
            }}
        }} else if (window.set{ns}Speed) {{
            // No select rendered (unusual); update JS state only, no server persist
            window.set{ns}Speed(speed);
        }}
    }};

    window.cycle{ns}SpeedUp = function() {{
        var speeds = {speeds_js};
        var current = (window.{sk} && window.{sk}.playbackSpeed) || 1.0;
        for (var i = 0; i < speeds.length; i++) {{
            if (speeds[i] > current + 1e-6) {{ window.cycle{ns}SpeedTo(speeds[i]); return; }}
        }}
        // Already at max; clamp (no-op)
    }};

    window.cycle{ns}SpeedDown = function() {{
        var speeds = {speeds_js};
        var current = (window.{sk} && window.{sk}.playbackSpeed) || 1.0;
        for (var i = speeds.length - 1; i >= 0; i--) {{
            if (speeds[i] < current - 1e-6) {{ window.cycle{ns}SpeedTo(speeds[i]); return; }}
        }}
        // Already at min; clamp (no-op)
    }};""")

    if config.enable_replay:
        parts.append(f"""window.replay{ns}Segment = function() {{
        var s = window.{sk};
        if (s.currentSegment) {{
            s.lastPlayedIndex = null;
            var c = s.currentSegment;
            if (c.indicator) c.indicator.style.visibility = 'visible';
            window.play{ns}Segment(c.bufferIndex, c.start, c.end, c.indicator);
        }}
    }};""")

    if config.enable_auto_nav:
        parts.append(f"""window.set{ns}AutoNavigate = function(flag) {{
        window.{sk}.autoNavigate = flag;
    }};""")

    return "\n\n    ".join(parts)


def generate_speed_change_js(
    config: WebAudioConfig,  # Instance configuration
    speed: float,            # New playback speed
) -> str:  # JS snippet: updates JS playbackSpeed via set{Ns}Speed
    """Generate the JS body returned by a consumer's `/speed_change` POST handler.

    Consumers wrap this in a `Script(...)` and return it so the client-side state
    updates after the server persists the new speed. Guarded with `if (window.set{Ns}Speed)`
    to tolerate the Script running before the web-audio script initializes.
    """
    ns = config.ns
    return f"if (window.set{ns}Speed) window.set{ns}Speed({speed});"

# %% ../nbs/js.ipynb #c5d6e7f8
def generate_focus_change(
    config: WebAudioConfig,  # Instance configuration
    focus_input_id: str,  # Hidden input ID for focused index
) -> str:  # JS focus change callback
    """Generate JS focus change callback for card stack integration."""
    sk = config.state_key
    ns = config.ns
    dbg = f"DEBUG_{config.namespace.upper()}_AUDIO"
    idx_attr = config.data_index_attr
    start_attr = config.data_start_attr
    end_attr = config.data_end_attr
    indicator_sel = config.indicator_selector
    
    return f"""window.on{ns}FocusChange = function(item, index, zoneId) {{
        var s = window.{sk};
        
        // Update hidden input
        var fi = document.getElementById('{focus_input_id}');
        if (fi) fi.value = index;
        
        var currentIndex = parseInt(item.dataset.segmentIndex || item.dataset.chunkIndex || index, 10);
        
        // Skip replay of same card
        if (s.lastPlayedIndex === currentIndex) {{
            if (window.{dbg}) console.log('[{ns}Audio] Same card, skipping replay');
            return;
        }}
        s.lastPlayedIndex = currentIndex;
        
        // Hide all indicators
        document.querySelectorAll('{indicator_sel}').forEach(function(el) {{
            el.style.visibility = 'hidden';
        }});
        
        // Read data attributes
        var startTime = parseFloat(item.dataset.{start_attr});
        var endTime = parseFloat(item.dataset.{end_attr});
        var bufferIndex = parseInt(item.dataset.{idx_attr} || '0', 10);
        
        if (isNaN(startTime) || isNaN(endTime) || endTime <= startTime) return;
        
        // Show indicator on current card
        var indicator = item.querySelector('{indicator_sel}');
        if (indicator) indicator.style.visibility = 'visible';
        
        window.play{ns}Segment(bufferIndex, startTime, endTime, indicator);
    }};"""

# %% ../nbs/js.ipynb #e7f8a9b0
def generate_htmx_settle_handler(
    config: WebAudioConfig,  # Instance configuration
    card_stack_id: str,  # Card stack container ID
) -> str:  # JS HTMX afterSettle handler
    """Generate HTMX afterSettle handler for card stack navigation.
    
    When `config.should_play_fn` is set, delegates the play guard to a consumer-defined
    window function (e.g., `window.shouldAlignPlay()`). Otherwise uses the default
    inline guard based on zone active state and auto-navigate flag.
    """
    ns = config.ns
    sk = config.state_key

    if config.should_play_fn:
        # Consumer-defined callback replaces the entire zone guard
        zone_guard = f"""
            if (typeof window.{config.should_play_fn} === 'function') {{
                if (!window.{config.should_play_fn}('{card_stack_id}')) return;
            }}"""
    elif config.enable_auto_nav:
        # Default: allow audio when zone is active or auto-navigate is running
        zone_guard = f"""
            // Play audio if zone is active or auto-navigate is running
            var zoneActive = true;
            if (window.kbNav) {{
                var kbState = window.kbNav.getState();
                if (kbState) zoneActive = (kbState.activeZoneId === '{card_stack_id}');
            }}
            if (!zoneActive && !(window.{sk} && window.{sk}.autoNavigate)) {{
                return;
            }}"""
    else:
        # Default: strict zone-active guard
        zone_guard = f"""
            // Only trigger audio for the active keyboard zone
            if (window.kbNav) {{
                var kbState = window.kbNav.getState();
                if (kbState && kbState.activeZoneId !== '{card_stack_id}') {{
                    return;
                }}
            }}"""

    return f"""(function() {{
        var handlerKey = '_{config.namespace}FocusSettleHandler';
        if (window[handlerKey]) {{
            document.body.removeEventListener('htmx:afterSettle', window[handlerKey]);
        }}
        window[handlerKey] = function(evt) {{
            var csEl = document.getElementById('{card_stack_id}');
            if (!csEl) return;
            {zone_guard}
            
            var focused = csEl.querySelector('[data-card-role="focused"]');
            if (focused) {{
                window.on{ns}FocusChange(focused, 0, '');
            }}
        }};
        document.body.addEventListener('htmx:afterSettle', window[handlerKey]);
    }})();"""

# %% ../nbs/js.ipynb #a9b0c1d2
def generate_web_audio_js(
    config: WebAudioConfig,  # Instance configuration
    focus_input_id: str,  # Hidden input ID for focused index
    card_stack_id: str,  # Card stack container ID
    nav_down_btn_id: str = "",  # Nav down button ID (for auto-navigate)
) -> str:  # Complete JS code for this instance
    """Generate the complete Web Audio API JS for a configured instance."""
    parts = [
        generate_state_init(config),
        generate_init_audio(config),
        generate_stop_audio(config),
        generate_play_segment(config, nav_down_btn_id),
        generate_focus_change(config, focus_input_id),
        generate_htmx_settle_handler(config, card_stack_id),
    ]
    
    optional = generate_optional_features(config)
    if optional:
        parts.append(optional)
    
    return "\n\n    ".join(parts)
