"""Configuration and HTML ID types for the Web Audio API manager"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/models.ipynb.

# %% auto #0
__all__ = ['WebAudioConfig', 'WebAudioHtmlIds']

# %% ../nbs/models.ipynb #c3d4e5f6
from dataclasses import dataclass

# %% ../nbs/models.ipynb #e5f6a7b8
@dataclass
class WebAudioConfig:
    """Configuration for a Web Audio API manager instance."""
    namespace: str                              # Unique prefix (e.g., "align", "review")
    indicator_selector: str                     # CSS selector for playing indicators
    data_index_attr: str = "audioFileIndex"     # Data attr name for buffer index
    data_start_attr: str = "startTime"          # Data attr name for start time
    data_end_attr: str = "endTime"              # Data attr name for end time
    enable_speed: bool = False                  # Playback speed support
    enable_replay: bool = False                 # Replay current segment support
    enable_auto_nav: bool = False               # Auto-navigate on completion support

    @property
    def ns(self) -> str:  # Capitalized namespace for JS function names
        """Capitalized namespace for JS function names (e.g., 'align' -> 'Align')."""
        return self.namespace.capitalize()

    @property
    def state_key(self) -> str:  # JS state object key
        """JS global state object key (e.g., '_webAudio_align')."""
        return f"_webAudio_{self.namespace}"

# %% ../nbs/models.ipynb #a7b8c9d0
class WebAudioHtmlIds:
    """HTML ID generators for Web Audio manager elements."""

    @staticmethod
    def audio_urls_input(
        namespace: str  # Instance namespace
    ) -> str:  # HTML ID for audio URLs hidden input
        """ID for the hidden input storing audio file URLs as JSON."""
        return f"sd-{namespace}-audio-urls"
